src/Vyper/SiteBundle/Form/TopType.php
<?php

namespace Vyper\SiteBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class TopType extends AbstractType
{
     /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', 'text', array('attr' => array('placeholder' => 'Title')))
            ->add('author', 'text', array('attr' => array('placeholder' => 'Artist')))
            ->add('link', 'text', array('required' => false, 'attr' => array('placeholder' => 'URL link to disc')))
            ->add('pictureID', 'text', array('required' => false, 'attr' => array('placeholder' => 'Picture ID')))
        ;

        // On ajoute une fonction qui va écouter un évènement
        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,    // 1er argument : L'évènement qui nous intéresse : ici, PRE_SET_DATA
            function(FormEvent $event) { // 2e argument : La fonction à exécuter lorsque l'évènement est déclenché
                // On récupère notre objet Advert sous-jacent
                $magazine = $event->getData();

                // Cette condition est importante, on en reparle plus loin
                if (null === $magazine) {
                    return; // On sort de la fonction sans rien faire lorsque $advert vaut null
                }
                if (null !== $magazine->getId() && !is_null($magazine->getPicture())) {

                    $event->getForm()->add('pictureID', 'text', array('data' => $magazine->getPicture()->getId()));
                }
            }
        );
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Vyper\SiteBundle\Entity\Top'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'vyper_sitebundle_top';
    }
}

src/Vyper/SiteBundle/Controller/AdminPartnerController.php
<?php
/**
 * Created by PhpStorm.
 * User: Saysa
 * Date: 10/08/14
 * Time: 13:55
 */

namespace Vyper\SiteBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Vyper\SiteBundle\Entity\Partner;
use Vyper\SiteBundle\Entity\Top;
use Vyper\SiteBundle\Form\PartnerType;
use Vyper\SiteBundle\Form\TopType;

class AdminPartnerController extends AdminCommonController {



    /**
     * @param Request $request
     * @param Partner $partner
     * @return \Symfony\Component\HttpFoundation\Response
     * @Security("has_role('ROLE_AUTHOR')")
     */
    public function updateAction(Request $request, Partner $partner)
    {
        $em = $this->getDoctrine()->getManager();
        $view = $this->container->get('saysa_view');

        $form = $this->createForm(new PartnerType, $partner);

        if ('POST' === $request->getMethod()) {

            $post_data = $request->request->get('vyper_sitebundle_partner');

            $form->submit($request);

            $picture = $em->getRepository('VyperSiteBundle:Picture')->find($post_data['pictureID']);

            $partner->setPicture($picture);

            if ($form->isValid()) {

                $em->flush();
            }

        }

        $view
            ->set('partner', $partner)
            ->set('active_editable', true)
            ->set('form', $form->createView())
        ;

        return $this->render('VyperSiteBundle:AdminPartner:update.html.twig', $view->getView());
    }

    public function showAllAction()
    {
        $view = $this->container->get('saysa_view');
        $em = $this->getDoctrine()->getManager();

        $type = $em->getRepository('VyperSiteBundle:PartnerType')->find(1);
        $partner_media    = $em->getRepository('VyperSiteBundle:Partner')->partnerMedia($type);
        $type = $em->getRepository('VyperSiteBundle:PartnerType')->find(2);
        $partner_event  = $em->getRepository('VyperSiteBundle:Partner')->partnerEvent($type);



        $view->set('partner_media',       $partner_media);
        $view->set('partner_event',     $partner_event);

        $view->set("active_editable",  true);

        return $this->render('VyperSiteBundle:AdminPartner:showAll.html.twig', $view->getView());
    }

    public function addAction(Request $request)
    {
        $view = $this->container->get('saysa_view');
        $partner = new Partner;
        $form = $this->createForm(new PartnerType, $partner);

        if ($request->getMethod() == 'POST') {

            $post_data = $request->request->get('vyper_sitebundle_partner');

            $form->submit($request);

            $picture = $this->getDoctrine()->getManager()->getRepository('VyperSiteBundle:Picture')->find($post_data['pictureID']);

            $partner->setPicture($picture);

            if ($form->isValid()) {

                $em = $this->getDoctrine()->getManager();
                $em->persist($partner);
                $em->flush();

                $request->getSession()->getFlashBag()->add('info', 'Partner added.');
                return $this->redirect($this->generateUrl('admin_show_partners'));
            }

        }

        $view
            ->set('form', $form->createView())
            ->set('active_editable', true)
        ;

        return $this->render('VyperSiteBundle:AdminPartner:add.html.twig', $view->getView());
    }

    public function deleteAction(Request $request, Partner $partner)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($partner);
        $em->flush();

        $request->getSession()->getFlashBag()->add('info', 'Partner deleted.');
        return $this->redirect($this->generateUrl('admin_show_partners'));
    }
} 

src/Vyper/SiteBundle/Resources/views/AdminPartner/add.html.twig
{% extends "VyperSiteBundle:layouts:admin.html.twig" %}

{% block title "ADMIN" %}

    {% block content %}
        <div class="row">
            <div class="col-lg-12">
                <div class="box">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Add Partner</h2>

                        <div class="box-icon">
                            <a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
                            <a href="#" class="btn-close"><i class="icon-remove"></i></a>
                        </div>
                    </div>
                    <form class="form-horizontal" method="post" {{ form_enctype(form) }}>

                        {{ form_widget(form._token) }}

                        <fieldset class="col-sm-12">

                            <div class="row">
                                <div class="col-lg-4">
                                    <!-- Title -->
                                    <div class="row">
                                        <div class="form-group col-lg-9{% if error_name is defined %} has-error{% endif %}">
                                            {{ form_label(form.name, "Name *") }}
                                            <div class="controls">
                                                {{ form_widget(form.name, {  'attr': {'class': 'form-control'} }) }}
                                                {{ form_errors(form.name) }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <!-- Link -->
                                    <div class="row">
                                        <div class="form-group col-lg-9{% if error_name is defined %} has-error{% endif %}">
                                            {{ form_label(form.link, "Link *") }}
                                            <div class="controls">
                                                {{ form_widget(form.link, {  'attr': {'class': 'form-control'} }) }}
                                                {{ form_errors(form.link) }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>



                            <div class="row">
                                <div class="col-lg-4">
                                    <!-- Type -->
                                    <div class="row">
                                        <div class="form-group col-lg-9{% if error_name is defined %} has-error{% endif %}">
                                            {{ form_label(form.type, "Type *") }}
                                            <div class="controls">
                                                {{ form_widget(form.type, {  'attr': {'class': 'form-control', 'data-rel': 'chosen'} }) }}
                                                {{ form_errors(form.type) }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4">

                                </div>
                            </div>




                            <div class="row">
                                <!-- Related Picture -->
                                <div class="form-group col-lg-3">
                                    {{ form_label(form.pictureID, "Picture ID *") }}
                                    <div class="controls">
                                        {{ form_widget(form.pictureID, { 'attr': {'class': 'form-control'} }) }}
                                        <a href="{{ path('admin_show_pictures') }}" target="_blank">View Pictures</a>
                                        {{ form_errors(form.pictureID) }}
                                    </div>
                                </div>
                            </div>

                            <div class="form-actions">
                                <input type="hidden" name="add" value="add">
                                <button type="submit" class="btn btn-primary">Save</button>

                            </div>

                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    {% endblock %}

src/Vyper/SiteBundle/Resources/views/AdminPartner/showAll.html.twig
{% extends "VyperSiteBundle:layouts:admin.html.twig" %}

{% block title "ADMIN" %}

    {% block content %}


        <div class="row">
            <div class="col-lg-12">
                <div class="box">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Production et médias</h2>
                        <div class="box-icon">
                            <a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
                            <a href="#" class="btn-close"><i class="icon-remove"></i></a>
                        </div>
                    </div>
                    <div class="box-content">

                        {# On affiche tous les messages flash dont le nom est « info » #}
                        {% for message in app.session.flashbag.get('info') %}
                            <div class="alert alert-info">{{ message }}</div>
                        {% endfor %}

                        <div class="pull-right">
                            <a href="{{ path('admin_add_partner') }}">
                                <button class="btn btn-small btn-primary"><i class="icon-plus"></i> add</button>
                            </a>
                        </div>


                        <hr>

                        <table class="table table-striped table-bordered bootstrap-datatable datatable" id="jquery-container">
                            <thead>
                            <tr>

                                <th>Logo</th>
                                <th>Artist</th>
                                <th>Modify</th>
                                <th>Delete</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for partner in partner_media %}
                                <tr>

                                    <td>
                                        <img src="{{ asset(partner.picture.getPath('75-75')) }}" alt="" />
                                    </td>
                                    <td>
                                        {{ partner.name }}
                                    </td>
                                    <td><a class="btn btn-info" href="{{ path('admin_update_partner', {'id': partner.getId}) }}"><i class="icon-edit "></i></a></td>
                                    <td><a class="btn btn-danger" href="{{ path('admin_delete_partner', {'id': partner.getId}) }}"><i class="icon-trash "></i></a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="box">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Evénements</h2>
                        <div class="box-icon">
                            <a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
                            <a href="#" class="btn-close"><i class="icon-remove"></i></a>
                        </div>
                    </div>
                    <div class="box-content">

                        <div class="pull-right">
                            <a href="{{ path('admin_add_partner') }}">
                                <button class="btn btn-small btn-primary"><i class="icon-plus"></i> add</button>
                            </a>
                        </div>


                        <hr>

                        <table class="table table-striped table-bordered bootstrap-datatable datatable" id="jquery-container">
                            <thead>
                            <tr>

                                <th>Logo</th>
                                <th>Artist</th>
                                <th>Modify</th>
                                <th>Delete</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for partner in partner_event %}
                                <tr>

                                    <td>
                                        <img src="{{ asset(partner.picture.getPath('75-75')) }}" alt="" />
                                    </td>
                                    <td>
                                        {{ partner.name }}
                                    </td>
                                    <td><a class="btn btn-info" href="{{ path('admin_update_partner', {'id': partner.getId}) }}"><i class="icon-edit "></i></a></td>
                                    <td><a class="btn btn-danger" href="{{ path('admin_delete_partner', {'id': partner.getId}) }}"><i class="icon-trash "></i></a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>




    {% endblock %}

src/Vyper/SiteBundle/Resources/views/AdminPartner/update.html.twig
{% extends "VyperSiteBundle:layouts:admin.html.twig" %}

{% block title "ADMIN" %}

    {% block content %}
        <div class="row">
            <div class="col-lg-12">
                <div class="box">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Update : {{ partner.name }}</h2>

                        <div class="box-icon">
                            <a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
                            <a href="#" class="btn-close"><i class="icon-remove"></i></a>
                        </div>
                    </div>
                    <div class="box-content">
                        <form class="form-horizontal" method="post" {{ form_enctype(form) }}>

                            {{ form_widget(form._token) }}

                            <fieldset class="col-sm-12">

                                <div class="row">
                                    <div class="col-lg-4">
                                        <!-- Title -->
                                        <div class="row">
                                            <div class="form-group col-lg-9{% if error_name is defined %} has-error{% endif %}">
                                                {{ form_label(form.name, "Name *") }}
                                                <div class="controls">
                                                    {{ form_widget(form.name, {  'attr': {'class': 'form-control'} }) }}
                                                    {{ form_errors(form.name) }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <!-- Link -->
                                        <div class="row">
                                            <div class="form-group col-lg-9{% if error_name is defined %} has-error{% endif %}">
                                                {{ form_label(form.link, "Link *") }}
                                                <div class="controls">
                                                    {{ form_widget(form.link, {  'attr': {'class': 'form-control'} }) }}
                                                    {{ form_errors(form.link) }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-lg-4">
                                        <!-- Type -->
                                        <div class="row">
                                            <div class="form-group col-lg-9{% if error_name is defined %} has-error{% endif %}">
                                                {{ form_label(form.type, "Type *") }}
                                                <div class="controls">
                                                    {{ form_widget(form.type, {  'attr': {'class': 'form-control', 'data-rel': 'chosen'} }) }}
                                                    {{ form_errors(form.type) }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">

                                    </div>
                                </div>



                                <div class="row">
                                    <!-- Related Picture -->
                                    <div class="form-group col-lg-3">
                                        {{ form_label(form.pictureID, "Picture ID *") }}
                                        <div class="controls">
                                            {{ form_widget(form.pictureID, { 'attr': {'class': 'form-control'} }) }}
                                            <a href="{{ path('admin_show_pictures') }}" target="_blank">View Pictures</a>
                                            {{ form_errors(form.pictureID) }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-actions">
                                    <input type="hidden" name="add" value="add">
                                    <button type="submit" class="btn btn-primary">Save</button>

                                </div>

                            </fieldset>

                        </form>
                    </div>
                </div>
            </div>
        </div>



    {% endblock %}